title: Information Artist
logo: /assets/css/Logo.png
description: Think Visually. Lead Humanly. Change Meaningfully.
author: Ruchira Parchur
google_analytics:
theme: jekyll-theme-minimal
header_pages:
  - README.md
  - coaching/README.md
  - change-management/README.md
  - agility/README.md
  - people-management/README.md
  - downloads/README.md
